from __future__ import annotations
from typing import Any, Protocol

class StateRepository(Protocol):
    def put_run(self, run_id: str, value: Any) -> None: ...
    def get_run(self, run_id: str) -> Any | None: ...
    def list_runs(self) -> tuple[Any, ...]: ...
    def put_comparison(self, comparison_id: str, value: Any) -> None: ...
    def get_comparison(self, comparison_id: str) -> Any | None: ...
    def list_comparisons(self) -> tuple[Any, ...]: ...

__all__ = ["StateRepository"]
