"""QCOL model-plugin registry public API with lazy scientific imports.

Keeping package import lightweight allows the FastAPI service, health endpoint,
and portable client to start before a run imports Cirq/OpenFermion.  Scientific
objects are loaded only when explicitly requested.
"""
from __future__ import annotations

from importlib import import_module
from typing import Any

__version__ = "1.25.0"

_LAZY_EXPORTS = {
    "ModelPlugin": ("qcol.plugin_api", "ModelPlugin"),
    "TaskPlugin": ("qcol.plugin_api", "TaskPlugin"),
    "ExecutionAdapter": ("qcol.execution", "ExecutionAdapter"),
    "public_plugin_registry": ("qcol.plugin_registry", "public_plugin_registry"),
    "ModelContract": ("qcol.model_contracts", "ModelContract"),
    "ModelClassificationContract": ("qcol.model_contracts", "ModelClassificationContract"),
    "ModelInstance": ("qcol.model_contracts", "ModelInstance"),
    "CapabilityReport": ("qcol.model_contracts", "CapabilityReport"),
    "ResolvedModelPlan": ("qcol.model_contracts", "ResolvedModelPlan"),
    "QuantumRealizationArtifact": ("qcol.model_contracts", "QuantumRealizationArtifact"),
    "get_model_contract": ("qcol.model_registry", "get_model_contract"),
    "list_model_contracts": ("qcol.model_registry", "list_model_contracts"),
    "public_model_registry": ("qcol.model_registry", "public_model_registry"),
    "public_model_ui_schema": ("qcol.model_ui_schema", "public_model_ui_schema"),
    "public_qho_ui_catalog": ("qcol.model_ui_schema", "public_qho_ui_catalog"),
    "validate_qho_ui_catalog": ("qcol.model_ui_schema", "validate_qho_ui_catalog"),
    "public_policy_catalog": ("qcol.policy_registries", "public_policy_catalog"),
    "ResourceEstimationRuleContract": ("qcol.resource_rules", "ResourceEstimationRuleContract"),
    "ResourcePolicyRuleProfile": ("qcol.resource_rules", "ResourcePolicyRuleProfile"),
    "ResourceRuleEvaluation": ("qcol.resource_rules", "ResourceRuleEvaluation"),
    "public_resource_rule_catalog": ("qcol.resource_rules", "public_resource_rule_catalog"),
    "resource_rule_catalog_fingerprint": ("qcol.resource_rules", "resource_rule_catalog_fingerprint"),
    "validate_resource_rule_registry": ("qcol.resource_rules", "validate_resource_rule_registry"),
    "SemanticOwnerContract": ("qcol.semantic_authority", "SemanticOwnerContract"),
    "SemanticFactContract": ("qcol.semantic_authority", "SemanticFactContract"),
    "SemanticDerivationRecord": ("qcol.semantic_authority", "SemanticDerivationRecord"),
    "public_semantic_authority_catalog": ("qcol.semantic_authority", "public_semantic_authority_catalog"),
    "semantic_authority_catalog_fingerprint": ("qcol.semantic_authority", "semantic_authority_catalog_fingerprint"),
    "validate_semantic_authority_catalog": ("qcol.semantic_authority", "validate_semantic_authority_catalog"),
    "semantic_leakage_audit": ("qcol.semantic_authority", "semantic_leakage_audit"),
    "build_scientific_realization_payload": ("qcol.semantic_identity", "build_scientific_realization_payload"),
    "scientific_realization_fingerprint": ("qcol.semantic_identity", "scientific_realization_fingerprint"),
    "build_execution_identity_payload": ("qcol.semantic_identity", "build_execution_identity_payload"),
    "execution_fingerprint": ("qcol.semantic_identity", "execution_fingerprint"),
    "ExecutionEvidenceIdentity": ("qcol.evidence_transfer", "ExecutionEvidenceIdentity"),
    "assess_execution_evidence_transferability": ("qcol.evidence_transfer", "assess_execution_evidence_transferability"),
    "public_execution_evidence_transferability_contract": ("qcol.evidence_transfer", "public_execution_evidence_transferability_contract"),
    "public_environment_scope_policy": ("qcol.environment_gate", "public_environment_scope_policy"),
    "public_unified_freeze_sequence_contract": ("qcol.freeze_sequence", "public_unified_freeze_sequence_contract"),
    "ExecutionAdapterDescriptor": ("qcol.execution", "ExecutionAdapterDescriptor"),
    "CanonicalExecutionResult": ("qcol.execution", "CanonicalExecutionResult"),
    "get_execution_adapter": ("qcol.execution", "get_execution_adapter"),
    "public_execution_adapter_catalog": ("qcol.execution", "public_execution_adapter_catalog"),
    "run_pipeline_with_execution_adapter": ("qcol.execution", "run_pipeline_with_execution_adapter"),
    "resolve_model": ("qcol.resolver", "resolve_model"),
    "build_quantum_realization": ("qcol.realization", "build_quantum_realization"),
    "resolve_request_to_quantum_realization": ("qcol.realization", "resolve_request_to_quantum_realization"),
    "TaskContract": ("qcol.task_contracts", "TaskContract"),
    "TaskInstance": ("qcol.task_contracts", "TaskInstance"),
    "TaskExecutionPlan": ("qcol.task_contracts", "TaskExecutionPlan"),
    "ResolvedModelTaskPlan": ("qcol.task_contracts", "ResolvedModelTaskPlan"),
    "get_task_contract": ("qcol.task_registry", "get_task_contract"),
    "public_task_registry": ("qcol.task_registry", "public_task_registry"),
    "public_model_task_matrix": ("qcol.model_task_matrix", "public_model_task_matrix"),
    "resolve_model_task": ("qcol.model_task_resolver", "resolve_model_task"),
    "GeneralSpinOrbitalModelContract": ("qcol.spin_orbital", "GeneralSpinOrbitalModelContract"),
    "SpinOrbitalInstance": ("qcol.spin_orbital", "SpinOrbitalInstance"),
    "FermionToQubitMappingPlugin": ("qcol.mappings", "FermionToQubitMappingPlugin"),
    "JWMappingPlugin": ("qcol.mappings", "JWMappingPlugin"),
    "BKMappingPlugin": ("qcol.mappings", "BKMappingPlugin"),
    "MappingCapabilityReport": ("qcol.mappings", "MappingCapabilityReport"),
    "MappingResourceReport": ("qcol.mappings", "MappingResourceReport"),
    "MappingComparisonReport": ("qcol.mappings", "MappingComparisonReport"),
    "public_mapping_registry": ("qcol.mappings", "public_mapping_registry"),
    "MappingPolicyContract": ("qcol.mapping_policies", "MappingPolicyContract"),
    "ModeOrderingContract": ("qcol.realization_policies", "ModeOrderingContract"),
    "EncodingContext": ("qcol.realization_policies", "EncodingContext"),
    "SectorEncodingProfile": ("qcol.realization_policies", "SectorEncodingProfile"),
    "StatePreparationPolicyContract": ("qcol.realization_policies", "StatePreparationPolicyContract"),
    "AnsatzPolicyContract": ("qcol.realization_policies", "AnsatzPolicyContract"),
    "MeasurementPolicyContract": ("qcol.realization_policies", "MeasurementPolicyContract"),
    "ReferencePolicyContract": ("qcol.realization_policies", "ReferencePolicyContract"),
    "VerificationPolicyContract": ("qcol.realization_policies", "VerificationPolicyContract"),
    "ToleranceProfile": ("qcol.acceptance", "ToleranceProfile"),
    "public_declarative_policy_contract_catalog": ("qcol.policy_contract_catalog", "public_declarative_policy_contract_catalog"),
    "policy_contract_catalog_fingerprint": ("qcol.policy_contract_catalog", "policy_contract_catalog_fingerprint"),
    "validate_declarative_policy_contracts": ("qcol.policy_contract_catalog", "validate_declarative_policy_contracts"),
    "MappingFamily": ("qcol.mapping_policies", "MappingFamily"),
    "MappingScope": ("qcol.mapping_policies", "MappingScope"),
    "AlgebraScope": ("qcol.mapping_policies", "AlgebraScope"),
    "PolicyStatus": ("qcol.mapping_policies", "PolicyStatus"),
    "CheckStatus": ("qcol.mapping_policies", "CheckStatus"),
    "Severity": ("qcol.mapping_policies", "Severity"),
    "GateApplicability": ("qcol.mapping_policies", "GateApplicability"),
    "AnsatzSemanticClass": ("qcol.mapping_policies", "AnsatzSemanticClass"),
    "SectorRepresentationKind": ("qcol.mapping_policies", "SectorRepresentationKind"),
    "EvidenceFreshnessStatus": ("qcol.mapping_policies", "EvidenceFreshnessStatus"),
    "DecisionStatus": ("qcol.mapping_policies", "DecisionStatus"),
    "VersionedIdentifier": ("qcol.mapping_policies", "VersionedIdentifier"),
    "public_mapping_realization_vocabulary": ("qcol.mapping_policies", "public_mapping_realization_vocabulary"),
    "vocabulary_fingerprint": ("qcol.mapping_policies", "vocabulary_fingerprint"),
    "validate_mapping_realization_vocabulary": ("qcol.mapping_policies", "validate_mapping_realization_vocabulary"),
    "public_mapping_realization_baseline": ("qcol.acceptance", "public_mapping_realization_baseline"),
    "baseline_fingerprint": ("qcol.acceptance", "baseline_fingerprint"),
    "CompatibilityFailureCode": ("qcol.compatibility", "CompatibilityFailureCode"),
    "public_failure_code_registry": ("qcol.compatibility", "public_failure_code_registry"),
    "BindingKind": ("qcol.implementation_bindings", "BindingKind"),
    "BindingFailureCode": ("qcol.implementation_bindings", "BindingFailureCode"),
    "ImplementationBindingContract": ("qcol.implementation_bindings", "ImplementationBindingContract"),
    "BindingRequirement": ("qcol.implementation_bindings", "BindingRequirement"),
    "BindingResolutionReport": ("qcol.implementation_bindings", "BindingResolutionReport"),
    "ResolvedImplementation": ("qcol.implementation_bindings", "ResolvedImplementation"),
    "ResolvedBindingPlan": ("qcol.implementation_bindings", "ResolvedBindingPlan"),
    "ImplementationBindingRegistry": ("qcol.implementation_bindings", "ImplementationBindingRegistry"),
    "DeclarativePolicyContractRegistry": ("qcol.implementation_bindings", "DeclarativePolicyContractRegistry"),
    "public_implementation_binding_catalog": ("qcol.implementation_bindings", "public_implementation_binding_catalog"),
    "implementation_binding_catalog_fingerprint": ("qcol.implementation_bindings", "implementation_binding_catalog_fingerprint"),
    "validate_implementation_binding_registry": ("qcol.implementation_bindings", "validate_implementation_binding_registry"),
    "CompatibilityRulePhase": ("qcol.compatibility", "CompatibilityRulePhase"),
    "CompatibilityParticipant": ("qcol.compatibility", "CompatibilityParticipant"),
    "CompatibilityRuleContract": ("qcol.compatibility", "CompatibilityRuleContract"),
    "RuleEvaluationContext": ("qcol.compatibility", "RuleEvaluationContext"),
    "PredicateResult": ("qcol.compatibility", "PredicateResult"),
    "CompatibilityCheckResult": ("qcol.compatibility", "CompatibilityCheckResult"),
    "CompatibilityRuleEvaluationReport": ("qcol.compatibility", "CompatibilityRuleEvaluationReport"),
    "CompatibilityRuleRegistry": ("qcol.compatibility", "CompatibilityRuleRegistry"),
    "build_wp4_rule_registry": ("qcol.compatibility", "build_wp4_rule_registry"),
    "public_compatibility_rule_catalog": ("qcol.compatibility", "public_compatibility_rule_catalog"),
    "compatibility_rule_catalog_fingerprint": ("qcol.compatibility", "compatibility_rule_catalog_fingerprint"),
    "validate_compatibility_rule_registry": ("qcol.compatibility", "validate_compatibility_rule_registry"),
    "RealizationTaskMode": ("qcol.realization_variants", "RealizationTaskMode"),
    "ResolutionStatus": ("qcol.realization_variants", "ResolutionStatus"),
    "RuntimeEntryStatus": ("qcol.realization_variants", "RuntimeEntryStatus"),
    "RuntimePath": ("qcol.realization_variants", "RuntimePath"),
    "RealizationCandidate": ("qcol.realization_variants", "RealizationCandidate"),
    "CompatibilityDiagnostic": ("qcol.realization_variants", "CompatibilityDiagnostic"),
    "CompatibilityReport": ("qcol.realization_variants", "CompatibilityReport"),
    "ResourceReport": ("qcol.realization_variants", "ResourceReport"),
    "AcceptanceEvidenceStatus": ("qcol.realization_variants", "AcceptanceEvidenceStatus"),
    "RuntimeEntryDecision": ("qcol.realization_variants", "RuntimeEntryDecision"),
    "ResolvedRealizationVariant": ("qcol.realization_variants", "ResolvedRealizationVariant"),
    "RealizationResolution": ("qcol.realization_variants", "RealizationResolution"),
    "RealizationVariantResolver": ("qcol.realization_variants", "RealizationVariantResolver"),
    "resolve_realization_variant": ("qcol.realization_variants", "resolve_realization_variant"),
    "dispatch_resolved_variant": ("qcol.realization_variants", "dispatch_resolved_variant"),
    "public_realization_resolver_catalog": ("qcol.realization_variants", "public_realization_resolver_catalog"),
    "realization_resolver_catalog_fingerprint": ("qcol.realization_variants", "realization_resolver_catalog_fingerprint"),
    "validate_realization_resolver": ("qcol.realization_variants", "validate_realization_resolver"),
    "AcceptanceEvidenceFingerprint": ("qcol.acceptance", "AcceptanceEvidenceFingerprint"),
    "AcceptanceEvidenceRecord": ("qcol.acceptance", "AcceptanceEvidenceRecord"),
    "FingerprintComparisonReport": ("qcol.acceptance", "FingerprintComparisonReport"),
    "DeclaredScaleContract": ("qcol.acceptance", "DeclaredScaleContract"),
    "DependencyFingerprint": ("qcol.acceptance", "DependencyFingerprint"),
    "compare_acceptance_fingerprints": ("qcol.acceptance", "compare_acceptance_fingerprints"),
    "public_acceptance_fingerprint_catalog": ("qcol.acceptance", "public_acceptance_fingerprint_catalog"),
    "acceptance_fingerprint_catalog_fingerprint": ("qcol.acceptance", "acceptance_fingerprint_catalog_fingerprint"),
    "AcceptanceGateKind": ("qcol.acceptance", "AcceptanceGateKind"),
    "AcceptanceGateContract": ("qcol.acceptance", "AcceptanceGateContract"),
    "AcceptanceHarnessCase": ("qcol.acceptance", "AcceptanceHarnessCase"),
    "AcceptanceHarnessReport": ("qcol.acceptance", "AcceptanceHarnessReport"),
    "GenericThreeGateAcceptanceHarness": ("qcol.acceptance", "GenericThreeGateAcceptanceHarness"),
    "public_acceptance_harness_catalog": ("qcol.acceptance", "public_acceptance_harness_catalog"),
    "acceptance_harness_catalog_fingerprint": ("qcol.acceptance", "acceptance_harness_catalog_fingerprint"),
    "JW_POLICY_ID": ("qcol.mapping_policies.profiles", "JW_POLICY_ID"),
    "JW_CONVENTION_ID": ("qcol.mapping_policies.profiles", "JW_CONVENTION_ID"),
    "BK_POLICY_ID": ("qcol.mapping_policies.profiles", "BK_POLICY_ID"),
    "BK_CONVENTION_ID": ("qcol.mapping_policies.profiles", "BK_CONVENTION_ID"),
    "build_jw_mapping_policy": ("qcol.mapping_policies.profiles", "build_jw_mapping_policy"),
    "build_bk_mapping_policy": ("qcol.mapping_policies.profiles", "build_bk_mapping_policy"),
    "public_spin_orbital_mapping_migration_catalog": ("qcol.mapping_policies.profiles", "public_spin_orbital_mapping_migration_catalog"),
    "spin_orbital_mapping_migration_catalog_fingerprint": ("qcol.mapping_policies.profiles", "spin_orbital_mapping_migration_catalog_fingerprint"),
    "validate_spin_orbital_mapping_migration": ("qcol.mapping_policies.profiles", "validate_spin_orbital_mapping_migration"),
    "public_a3_2b_exit_decision": ("qcol.mapping_policies.profiles", "public_a3_2b_exit_decision"),
    "PairMappingMigrationProfile": ("qcol.mapping_policies.profiles", "PairMappingMigrationProfile"),
    "build_pair_mapping_policy": ("qcol.mapping_policies.profiles", "build_pair_mapping_policy"),
    "public_pair_mapping_migration_catalog": ("qcol.mapping_policies.profiles", "public_pair_mapping_migration_catalog"),
    "pair_mapping_migration_catalog_fingerprint": ("qcol.mapping_policies.profiles", "pair_mapping_migration_catalog_fingerprint"),
    "validate_pair_mapping_migration": ("qcol.mapping_policies.profiles", "validate_pair_mapping_migration"),
    "WP11_ANSATZ_POLICY_ID": ("qcol.mapping_policies.profiles", "WP11_ANSATZ_POLICY_ID"),
    "WP11_VARIANT_ID": ("qcol.mapping_policies.profiles", "WP11_VARIANT_ID"),
    "build_wp11_ansatz_policy": ("qcol.mapping_policies.profiles", "build_wp11_ansatz_policy"),
    "build_wp11_acceptance_fingerprint": ("qcol.mapping_policies.profiles", "build_wp11_acceptance_fingerprint"),
    "build_wp11_acceptance_record": ("qcol.mapping_policies.profiles", "build_wp11_acceptance_record"),
    "public_wp11_jw_accepted_composition_catalog": ("qcol.mapping_policies.profiles", "public_wp11_jw_accepted_composition_catalog"),
    "wp11_jw_accepted_composition_catalog_fingerprint": ("qcol.mapping_policies.profiles", "wp11_jw_accepted_composition_catalog_fingerprint"),
    "validate_wp11_jw_accepted_composition": ("qcol.mapping_policies.profiles", "validate_wp11_jw_accepted_composition"),
    "evaluate_jw_generator_conformance": ("qcol.acceptance", "evaluate_jw_generator_conformance"),
    "evaluate_wp11_cell_acceptance": ("qcol.acceptance", "evaluate_wp11_cell_acceptance"),
    "evaluate_wp11_acceptance": ("qcol.acceptance", "evaluate_wp11_acceptance"),
    "AdvisorContext": ("qcol.advisor", "AdvisorContext"),
    "AdvisorRuleContract": ("qcol.advisor", "AdvisorRuleContract"),
    "RecommendationCard": ("qcol.advisor", "RecommendationCard"),
    "AdvisorReport": ("qcol.advisor", "AdvisorReport"),
    "CandidateRequestPlan": ("qcol.advisor", "CandidateRequestPlan"),
    "RunComparison": ("qcol.comparison", "RunComparison"),
    "ComparisonOutcome": ("qcol.comparison", "ComparisonOutcome"),
    "compare_runs": ("qcol.comparison", "compare_runs"),
    "public_phase_c_catalog": ("qcol.comparison", "public_phase_c_catalog"),
    "build_advisor_context_from_run_payload": ("qcol.advisor", "build_advisor_context_from_run_payload"),
    "evaluate_advisor_context": ("qcol.advisor", "evaluate_advisor_context"),
    "advise_run_payload": ("qcol.advisor", "advise_run_payload"),
    "prepare_candidate_request_plan": ("qcol.advisor", "prepare_candidate_request_plan"),
    "public_deterministic_advisor_catalog": ("qcol.advisor", "public_deterministic_advisor_catalog"),
    "deterministic_advisor_catalog_fingerprint": ("qcol.advisor", "deterministic_advisor_catalog_fingerprint"),
    "validate_deterministic_advisor_catalog": ("qcol.advisor", "validate_deterministic_advisor_catalog"),
    "deterministic_advisor_rule_catalog_fingerprint": ("qcol.advisor", "deterministic_advisor_rule_catalog_fingerprint"),
    "export_phase_b_advisor_evidence": ("qcol.advisor", "export_phase_b_advisor_evidence"),
    "PublicRealizationVariant": ("qcol.realization_variants", "PublicRealizationVariant"),
    "ModelTaskCellRealizationView": ("qcol.realization_variants", "ModelTaskCellRealizationView"),
    "public_model_task_realization_catalog": ("qcol.realization_variants", "public_model_task_realization_catalog"),
    "model_task_realization_catalog_fingerprint": ("qcol.realization_variants", "model_task_realization_catalog_fingerprint"),
    "validate_model_task_realization_catalog": ("qcol.realization_variants", "validate_model_task_realization_catalog"),
    "ScientificOwnerContract": ("qcol.governance", "ScientificOwnerContract"),
    "GovernedAssetRecord": ("qcol.governance", "GovernedAssetRecord"),
    "AcceptanceEvidenceOwnershipContract": ("qcol.governance", "AcceptanceEvidenceOwnershipContract"),
    "DeprecationRuleContract": ("qcol.governance", "DeprecationRuleContract"),
    "MigrationRuleContract": ("qcol.governance", "MigrationRuleContract"),
    "PublishedScientificStatusRecord": ("qcol.governance", "PublishedScientificStatusRecord"),
    "AllowedRequestPatchContract": ("qcol.governance", "AllowedRequestPatchContract"),
    "RequestPatchCandidate": ("qcol.governance", "RequestPatchCandidate"),
    "RequestPatchValidationReport": ("qcol.governance", "RequestPatchValidationReport"),
    "PhaseBHandoffContract": ("qcol.governance", "PhaseBHandoffContract"),
    "A32CReleaseDecision": ("qcol.governance", "A32CReleaseDecision"),
    "public_governance_catalog": ("qcol.governance", "public_governance_catalog"),
    "governance_catalog_fingerprint": ("qcol.governance", "governance_catalog_fingerprint"),
    "validate_wp13_governance_catalog": ("qcol.governance", "validate_wp13_governance_catalog"),
    "public_allowed_request_patch_registry": ("qcol.governance", "public_allowed_request_patch_registry"),
    "validate_advisor_request_patch": ("qcol.governance", "validate_advisor_request_patch"),
    "build_a3_2c_release_decision": ("qcol.governance", "build_a3_2c_release_decision"),
    "build_phase_b_handoff_contract": ("qcol.governance", "build_phase_b_handoff_contract"),
    "export_wp13_governance_evidence": ("qcol.governance", "export_wp13_governance_evidence"),
    "ProblemArtifact": ("qcol.contracts", "ProblemArtifact"),
    "RunResult": ("qcol.contracts", "RunResult"),
    "JourneyState": ("qcol.events", "JourneyState"),
    "PipelineEvent": ("qcol.events", "PipelineEvent"),
    "PipelineStreamUpdate": ("qcol.events", "PipelineStreamUpdate"),
    "PipelineFailure": ("qcol.failures", "PipelineFailure"),
    "CancellationToken": ("qcol.control", "CancellationToken"),
    "RunCancelled": ("qcol.control", "RunCancelled"),
    "run_pipeline": ("qcol.orchestrator", "run_pipeline"),
    "run_pipeline_controlled": ("qcol.orchestrator", "run_pipeline_controlled"),
    "run_pipeline_stream": ("qcol.orchestrator", "run_pipeline_stream"),
}

__all__ = ["__version__", *_LAZY_EXPORTS]


def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(name)
    module_name, attribute_name = target
    value = getattr(import_module(module_name), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
